CID-1624: Enforce branch name pattern

diff --git a/.github/workflows/gradle-build.yml b/.github/workflows/gradle-build.yml
--- a/.github/workflows/gradle-build.yml
+++ b/.github/workflows/gradle-build.yml
@@ -6,14 +6,24 @@ concurrency:
 
 on:
   push:
-    branches:
-      - main
-      - feature/**
   workflow_dispatch:
 
 jobs:
+  validation:
+    name: Branch name validation
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check branch name
+        run: |
+          if [[ "${{ github.ref }}" == "refs/heads/main" ]] || [[ "${{ github.head_ref }}" == feature/* ]] || [[ "${{ github.head_ref }}" == bug/* ]]; then
+            echo "Branch naming is correct!"
+          else
+            echo "Invalid branch name! Correct format: 'feature/<branch-name>' or 'bug/<branch-name>'"
+            exit 1
+          fi
   gradle-ci:
     name: Build and test
+    needs: validation
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
